[2024-12-28T17:02:20.450+0000] {processor.py:186} INFO - Started process (PID=1328) to work on /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:02:20.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/8.fail_retry.py for tasks to queue
[2024-12-28T17:02:20.452+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:02:20.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:02:20.460+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:02:20.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/8.fail_retry.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/8.fail_retry.py", line 10, in <module>
    retry_delay=timedelta(seconds=30)
                ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-12-28T17:02:20.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:02:20.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/8.fail_retry.py took 0.036 seconds
[2024-12-28T17:02:51.020+0000] {processor.py:186} INFO - Started process (PID=1401) to work on /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:02:51.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/8.fail_retry.py for tasks to queue
[2024-12-28T17:02:51.023+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:02:51.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:02:51.030+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:02:51.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/8.fail_retry.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/8.fail_retry.py", line 10, in <module>
    retry_delay=timedelta(seconds=30)
                ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-12-28T17:02:51.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:02:51.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/8.fail_retry.py took 0.038 seconds
[2024-12-28T17:03:09.710+0000] {processor.py:186} INFO - Started process (PID=1456) to work on /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:03:09.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/8.fail_retry.py for tasks to queue
[2024-12-28T17:03:09.713+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:03:09.721+0000] {processor.py:925} INFO - DAG(s) 'fail_and_retry' retrieved from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:03:09.811+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.810+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:fail_and_retry
[2024-12-28T17:03:09.819+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.818+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:fail_and_retry
[2024-12-28T17:03:09.824+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.824+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:fail_and_retry
[2024-12-28T17:03:09.830+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.830+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:fail_and_retry
[2024-12-28T17:03:09.835+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.835+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:fail_and_retry
[2024-12-28T17:03:09.841+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.840+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:fail_and_retry
[2024-12-28T17:03:09.846+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.846+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:fail_and_retry
[2024-12-28T17:03:09.847+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.847+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-28T17:03:09.857+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.857+0000] {dag.py:3262} INFO - Creating ORM DAG for fail_and_retry
[2024-12-28T17:03:09.866+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:09.866+0000] {dag.py:4180} INFO - Setting next_dagrun for fail_and_retry to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-12-28T17:03:09.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/8.fail_retry.py took 0.176 seconds
[2024-12-28T17:03:40.696+0000] {processor.py:186} INFO - Started process (PID=1533) to work on /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:03:40.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/8.fail_retry.py for tasks to queue
[2024-12-28T17:03:40.699+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:40.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:03:40.707+0000] {processor.py:925} INFO - DAG(s) 'fail_and_retry' retrieved from /opt/airflow/dags/8.fail_retry.py
[2024-12-28T17:03:40.724+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:40.724+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-28T17:03:40.746+0000] {logging_mixin.py:190} INFO - [2024-12-28T17:03:40.746+0000] {dag.py:4180} INFO - Setting next_dagrun for fail_and_retry to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-12-28T17:03:40.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/8.fail_retry.py took 0.073 seconds
